// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace specflowSudent
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("BDDTest elvira")]
    [NUnit.Framework.CategoryAttribute("feature_tag")]
    public partial class BDDTestElviraFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "14BDDTest.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BDDTest elvira", null, ProgrammingLanguage.CSharp, new string[] {
                        "feature_tag"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a search between two cities")]
        [NUnit.Framework.CategoryAttribute("basic")]
        public virtual void CreateASearchBetweenTwoCities()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a search between two cities", null, new string[] {
                        "basic"});
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
 testRunner.Given("I open elvira mav-start page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When("I create a search from Székesfehérvár to Sopron", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.And("I submit the search from", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then("the search result title should contain Székesfehérvár and Sopron", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a search between two cities using tables")]
        [NUnit.Framework.CategoryAttribute("tables")]
        public virtual void CreateASearchBetweenTwoCitiesUsingTables()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a search between two cities using tables", null, new string[] {
                        "tables"});
#line 14
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 15
 testRunner.Given("I open elvira mav-start page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "FromCity",
                        "ToCity",
                        "ViaCity"});
            table1.AddRow(new string[] {
                        "Szolnok",
                        "Debrecen",
                        "Hajdúszoboszló"});
#line 16
 testRunner.When("I create a search with the following parameters", ((string)(null)), table1, "When ");
#line 19
 testRunner.And("I submit the search from", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "cities"});
            table2.AddRow(new string[] {
                        "Szolnok"});
            table2.AddRow(new string[] {
                        "Debrecen"});
            table2.AddRow(new string[] {
                        "Hajdúszoboszló"});
#line 20
 testRunner.Then("the search result title should contain the following city names", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a search between two cities using tables using example table")]
        [NUnit.Framework.CategoryAttribute("tables")]
        [NUnit.Framework.TestCaseAttribute("Szolnok", "Debrecen", "Hajdúszoboszló", null)]
        [NUnit.Framework.TestCaseAttribute("Budapest", "Győr", "Tata", null)]
        public virtual void CreateASearchBetweenTwoCitiesUsingTablesUsingExampleTable(string fromCity, string toCity, string viaCity, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "tables"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a search between two cities using tables using example table", null, @__tags);
#line 28
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 29
 testRunner.Given("I open elvira mav-start page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "FromCity",
                        "ToCity",
                        "ViaCity"});
            table3.AddRow(new string[] {
                        string.Format("{0}", fromCity),
                        string.Format("{0}", toCity),
                        string.Format("{0}", viaCity)});
#line 30
 testRunner.When("I create a search with the following parameters", ((string)(null)), table3, "When ");
#line 33
 testRunner.And("I submit the search from", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "cities"});
            table4.AddRow(new string[] {
                        string.Format("{0}", fromCity)});
            table4.AddRow(new string[] {
                        string.Format("{0}", toCity)});
            table4.AddRow(new string[] {
                        string.Format("{0}", viaCity)});
#line 34
 testRunner.Then("the search result title should contain the following city names", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
