// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace specflowSudent
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("BeadandoTest forms")]
    [NUnit.Framework.CategoryAttribute("feature_tag")]
    public partial class BeadandoTestFormsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BeadandoTest.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BeadandoTest forms", null, ProgrammingLanguage.CSharp, new string[] {
                        "feature_tag"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Fill a microsoft forms survey using examples table")]
        [NUnit.Framework.CategoryAttribute("tables")]
        [NUnit.Framework.TestCaseAttribute("Megismerni a tesztelés világát elméleti és gyakorlati oldalról is.", "4", "3, 4, 4, 5", "2", "Pontosan olyan, mint ez a Web UI-s része volt a tárgynak.", "8", null)]
        [NUnit.Framework.TestCaseAttribute("Tesztelni!", "5", "5, 5, 5, 5", "1", "Pontosan olyan, mint ez a Web UI-s része volt a tárgynak.", "9", null)]
        public virtual void FillAMicrosoftFormsSurveyUsingExamplesTable(string firstAnswer, string secondAnswer, string thirdAnswer, string fourthAnswer, string fifthAnswer, string sixthAnswer, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "tables"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Fill a microsoft forms survey using examples table", null, @__tags);
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
 testRunner.Given("I open microsoft forms survey page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstAnswer",
                        "SecondAnswer",
                        "ThirdAnswer",
                        "FourthAnswer",
                        "FifthAnswer",
                        "SixthAnswer"});
            table5.AddRow(new string[] {
                        string.Format("{0}", firstAnswer),
                        string.Format("{0}", secondAnswer),
                        string.Format("{0}", thirdAnswer),
                        string.Format("{0}", fourthAnswer),
                        string.Format("{0}", fifthAnswer),
                        string.Format("{0}", sixthAnswer)});
#line 7
 testRunner.When("I fill the survey with the following parameters", ((string)(null)), table5, "When ");
#line 10
 testRunner.And("I submit the survey from", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then("the survey result should contain the tick symbol", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
